openapi: 3.0.1
info:
  title: New PEC Request
  description: API interation to generate a new PEC workflow, to perfrom the requested pre employment checks on a applicant. From ERP to PEC
  version: v0.1
servers:
- url: "{server}/xx/v2"
  description: default server
  variables:
    server:
      default: https://xxxx.x.xxx
paths:
  "/NewPECWorkflow":
    post:
      tags:
        - New applicant
      summary: Endpoint for creating new PEC workflow
      description: Parse data to create a new PEC workflow.
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PECRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulIntergrationResponce'
        '400':
          description: Payload Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
        '409':
          description: Idempotency Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
        '500':
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
    get:
      tags:
        - Applicant Update
      summary: Get update from PEC
      description: This will return the current of an PEC workflow given the submitted unique ID
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PECGetUpdate'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulIntergrationResponce'
        '400':
          description: Payload Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
        '409':
          description: Idempotency Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
        '500':
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnseccessfulIntergrationResponce'
components:
  schemas:
    UnseccessfulIntergrationResponce:
      title: Unsuccessful response to Vacancy data
      type: object
      properties:
        ErrorCode:
          title: Error Code
          type: integer
          description: the numeric error to pass back to the user
        Title:
          title: Error title
          description: the title of the error
          type: string
        Message:
          title: Error description
          type: string
          description: A description of the error
        ErrorDetailArray:
          title: Error Detail Array
          description: >-
            An array containing any extra details of the error, for example
            field names.
          type: array
          items:
            type: string
      description: An object containing the details of unsuccessful integration and error message.
    SuccessfulIntergrationResponce:
      title: Successful response to Vacancy data
      type: object
      properties:
        Message:
          title: Note
          type: string
          description: note
        PECWorkflowID:
          title: PEC Workflow ID
          description: The unique ID created by the PEC workflow for this new case
          type: string
        UniqueERPRequestID:
          title: Unique ERP Request ID
          description: The unique id created by the ERP system to identify this request.
          type: string
        PECStatus:
          title: PEC Status
          description: The status of the newly created PEC workflow 
          type: string
      description: Successful response message
    PECGetUpdate:
      title: PEC Update Request Object
      type: object
      properties:
        UniqueERPRequestID:
          title: Unique ERP Request ID
          description: The unique id created by the ERP system to identify this request.
          type: string
        PECWorkflowID:
          title: PEC Workflow ID
          description: The unique ID that was assigned to the PEC workflow on creation
          type: string
    PECRequest:
      title: PEC Request Object
      type: object
      properties:
        UniqueERPRequestID:
          title: Unique ERP Request ID
          description: The unique id created by the ERP system to identify this request.
          type: string
        PositionName:
          title: Position Name
          description: The name of the position the applicant will be associated with
          type: string
        Cluster:
          title: Cluster
          description: The name of the cluster the request id coming from
          type: string
        Department:
          title: Department
          description: The name of the department the position is with
          type: string
        Applicant:
          title: Applicant Details
          description: An object containing applicant details
          "$ref": "#/components/schemas/ApplicantOb"
        Checks:
          title: Checks
          description: An array of requested checks
          type: array
          items: 
            "$ref": "#/components/schemas/CheckOb"
    ApplicantOb:
      title: Applicant Object
      description: An object that is used to describe the properties of an applicant
      type: object
      properties:
        FirstName:
          title: First name
          description: The applicants first name
          type: string
        LastName: 
          title: Last name
          description: The applicants last name
          type: string
        PreferedName:
          title: Prefered name
          description: The applicants prefered name
          type: string
        Email:
          title: Email Address
          description: Email Address of applicant
          type: string
        DateOfBirth:
          title: Date of Birth 
          description: The applicants date of birth
          type: string
          format: date
    CheckOb:
      title: Check Object
      description: An object containing the details a requested checks
      type: object
      properties:
        CheckName:
          title: Check Name
          description: The name of the check requested
          type: string
        CheckLevel:
          title: Check Level
          description: The level of the requested check
          type: string


